# Generated by Django 4.2.11 on 2024-03-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid", models.BooleanField(default=False)),
                ("nickname", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="profile_pics"),
                ),
                ("ba_start_year", models.IntegerField(null=True)),
                ("ba_end_year", models.IntegerField(null=True)),
                ("ma_start_year", models.IntegerField(null=True)),
                ("ma_end_year", models.IntegerField(null=True)),
                ("phd_start_year", models.IntegerField(null=True)),
                ("phd_end_year", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
