# Generated by Django 4.2.11 on 2024-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(null=True),
        ),
    ]
