# Generated by Django 4.2.11 on 2024-04-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_alter_profile_ba_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ba_end_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ba_start_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ma_end_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ma_start_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phd_end_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phd_start_year',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='dbase.profile')),
            ],
        ),
    ]
