# Generated by Django 4.2.11 on 2024-06-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0005_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='city',
            new_name='subject',
        ),
    ]
