# Generated by Django 4.2.11 on 2024-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbase", "0008_profile_firstname_profile_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slogan",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
