# Generated by Django 4.2.11 on 2024-07-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0009_profile_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='phase',
            field=models.CharField(max_length=50),
        ),
    ]
