# Generated by Django 4.2.11 on 2024-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0013_alter_academic_end_date_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otherthings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
